### ISSUE TITLE
Currently not working

### ISSUE THREAD

**Issue by Onestay** [jerryteps/Crunchyroll-Unblocker#3]
I don't know if you've already read it in the ratings on the chrome web store but it's currently not working. 
I always get to the German site with the extension enabled.

**Comment by jkey** [comment]
There are error messages on the page used to generate the session id

```
Warning: implode(): Invalid arguments passed in /home/crunbloc/public_html/sess_id.php on line 4

Warning: implode(): Invalid arguments passed in /home/crunbloc/public_html/sess_id.php on line 13
403 Forbidden Date: Sun, 05 Fe
```

**Comment by Ar1sC** [comment]
Yep the page has some errors its not extension problem.

**Comment by Bazalia** [comment]
So we need to somehow create a page that will retrieve a US sses_id.

Possibly by running a server in the US that GETS the crunchyroll page then extracts sses_id cookie value.

But I don't know if that would work.

**Comment by Ar1sC** [comment]
The sess_id file still exist. So we just have to wait for crunchyroll to fix it.

**Comment by Bazalia** [comment]
Correct me if I am wrong. From my understanding, the sess_id file is made by the author Crunchyroll Unblocker and so Crunchyroll has nothing to do with it. But the author or whoever is hosting crunblocker.com has to fix it.

**Comment by philip93dk** [comment]
even if extension get fixed the website that hosts the US session id Expires the on 04-21

**Comment by jkey** [comment]
Perhaps my time on the weekend is enough and I can take the matter. If I can achieve something, I tell you.

**Comment by Onestay** [comment]
I will try to write something tomorrow. Shouldn't be too much work actually:
Just GET the crunchyroll.com site from somewhere located in the US (shouldn't be too hard if someone has a vps hosted in the US) and extract the session token from there.

**Comment by Onestay** [comment]
So I've played around a bit. I should be done in the next 2 to 3 days.

**Comment by Onestay** [comment]
I can't seem to get the session id cookie from a http get request. Did you guys have any luck?

**Comment by Bazalia** [comment]
In Javascript I can call document.cookie on crunchyroll.com page, but the returned structure doesn't contain sess_id. Not sure why sess_id cookie doesn't show up it might be hidden somehow. Maybe an extension can gain more privileges to read that cookie.

**Comment by Onestay** [comment]
Using the request module I only get two cookies which are "_cfduid" and "c_visitor"

**Comment by Onestay** [comment]
So it seems like when you use a session id on a logged in account it gets bound to your account. Be careful with not giving out two identical session ids. This could lead to a huge mess!

**Comment by jkey** [comment]
Do not forget that there is also the cloudflare check! Here a similar issue.
https://github.com/Godzil/Crunchy/issues/14#issuecomment-277936820

**Comment by Onestay** [comment]
Looks like it will be harder then expected...
I would like to see that PHP script

**Comment by jkey** [comment]
Maybe the server should be set up in nodejs.

**Comment by Onestay** [comment]
Well my biggest issue right now is not getting the session token. The chrome extension would be basically ready...

**Comment by Onestay** [comment]
So I'm able to get the session id now with the cloudscraper module. Thanks for pointing me to that issue @jkey

**Comment by davhuit** [comment]
@Onestay : I'm hoping you'll manage to make a new working plugin :)

**Comment by Onestay** [comment]
Well the current problem is that the cloudflare ddos protection is giving me a captcha on every second request which the module I'm using to bypass cloudflare ddos protection can't solve. My idea would be to proxy every request, but I'll have to see.

**Comment by jkey** [comment]
@Onestay : Don't you get a captcha from cloudflare? If you store the cookie in a cache and give in with each request, it should be no problem anymore.

**Comment by RubbixCube** [comment]
I just created a working implementation of retrieving the session ID. Thanks to @Onestay for mentioning the use of *cloudscraper* and @jkey for suggesting re-requesting the the webpage with the headers.

Below is the code for the node script...
```js
var request = require('request'), cloudscraper = require('cloudscraper');
var URL = 'http://www.crunchyroll.com';

//Initial request of the webpage
cloudscraper.get(URL, (err, resp, body) => {
    if(err) return console.log(err);
    if(resp.statusCode != 200) return console.log(resp.statusCode);

    //Store the __cfduid and c_visitor cookies to use them in the request later
    var headers = {};
    headers[resp.headers['set-cookie'][0].match(/(.*?)=(.*?);/)[1]] = resp.headers['set-cookie'][0].match(/(.*?)=(.*?);/)[2];
    headers[resp.headers['set-cookie'][1].match(/(.*?)=(.*?);/)[1]] = resp.headers['set-cookie'][1].match(/(.*?)=(.*?);/)[2];

    //Got the required headers from Cloudflare
    //Now to request the page again while supplying those headers

    cloudscraper.request({
        headers: headers,
        url: URL,
        method: 'GET'
    }, (_err, _resp, _body) => {
        if(_err) return console.log(_err);
        if(_resp.statusCode != 200) return console.log(_resp.statusCode);

        console.log(_resp.headers['set-cookie'][0].match(/(.*?)=(.*?);/)[2]);
    });
});
```

I can confirm that running the script on a US connection gives a US Session ID. I was able to modify the extension locally and access the anime that was previously missing.

**Comment by Onestay** [comment]
I've a running setup right now https://github.com/Onestay/CR-Unblocker/
It's not production ready yet. This was done pretty quickly. I will look over it and maybe publish it tomorrow or during the weekend. Feel free to contribute if you notice anything bad.

**Comment by davhuit** [comment]
How to install/run it?

**Comment by Onestay** [comment]
I'm going to publish it on the chrome Web store today.

**Comment by davhuit** [comment]
Okay :)

**Comment by davhuit** [comment]
Okay :)

It'll be called "cr-unblocker" I guess?

**Comment by Onestay** [comment]
I'm going to write it here and post it on /r/Crunchyroll

**Comment by Ar1sC** [comment]
How much you paying for the VPS?

**Comment by Onestay** [comment]
It's out!

https://chrome.google.com/webstore/detail/cr-unblocker/agapeeilkibacbfeijlidlgppmjaaijn

I''ve set it to unlisted and will only post it here for a short beta test.
If you find any errors please tell me!

**Comment by TheForcer** [comment]
Just installed the extension in Chrome, working great out of the box. Thanks a lot :)

**Comment by HyperMR** [comment]
Thank you for your hard work but i installed the new extension and it's not working

**Comment by Onestay** [comment]
@HyperMR what is happening? Could you give me some more details on your system?

**Comment by Onestay** [comment]
Also if you have any problems please post them to https://github.com/Onestay/CR-Unblocker/issues

**Comment by HyperMR** [comment]
I'm using a macbook and for some reason the extension doesn't seem to work i still get the country where I'm located

**Comment by davibu** [comment]
@HyperMR 
Did you delete your Crunchyroll cookies?
After that, did you re-enabled the english language?
I forgot the second one, but now it works :)

**Comment by HyperMR** [comment]
@davibu I did delete my cookies but how do I re-enable the English language?

**Comment by davibu** [comment]
@HyperMR 
On the bottom of the page is a language section ^^

**Comment by HyperMR** [comment]
@davibu oh thank you but its still not working :(

**Comment by Onestay** [comment]
@HyperMR try visiting chrome://extensions/ and click on "Background Page" for the CR-Unblocker. Are there any errors or other messages in the console?

**Comment by philip93dk** [comment]
thank you

**Comment by davhuit** [comment]
I can confirm the extension works for me, didn't even need to delete the cookies.

And I'm using it in Opera, using the extension which allow Chrome extensions to be installed on Opera.

**Comment by davhuit** [comment]
But I wonder if Crunchyroll didn't put some limitations for the IPs outside of USA.

Because with the unblocker, my speed is ~150k/s and is not enough to play an episode at 720p without buffering.

But if I use Opera's VPN, my speed is ~500ko/s which is far enough to play an episode at 720p without any buffering.

Did some other people noticed that too?

**Comment by Onestay** [comment]
I didn't notice anything. I can, with and without the unblocker, watch in 1080p

**Comment by Ar1sC** [comment]
@davhuit Nope , you dont even connect to a vpn with this extension, you just get the cookie.

**Comment by davhuit** [comment]
@Ar1sC : This is not what I said. I said with the unblocker, it buffer and with a VPN, it doesn't.

But I just tried without the unblocker and the VPN and it buffer, so it mean it's a general peering problem (saw several people in my country complaining about that) and so it's not related to the unblocker.

**Comment by patryk4815** [comment]
@Onestay, Thanks for setup secure server 👍 
New plugin work on macOS Sierra and Windows10 :)

**Comment by HyperMR** [comment]
@Onestay there isn't "Background Page" option only "Permissions" and "Details"

**Comment by Onestay** [comment]
@HyperMR there should be a option to turn on developer mode

**Comment by RubbixCube** [comment]
Aside from all the troubles some are having with the custom temporary extension.

Would you say that this issue has been resolved? Now that there is a working alternative...

**Comment by Onestay** [comment]
Yep, I guess we can say it's resolved. For any further issues with my extension please create an issue here:  https://github.com/Onestay/CR-Unblocker/issues
